name: kitematic
version: 0.0.1
summary: kitematic snap
description: |
  kitematic snap

architectures:
  - build-on: amd64
    run-on: amd64
base: core18
grade: stable
confinement: classic

parts:
  kitematic:
    plugin: dump
    source: snap/local/deb/Kitematic-0.17.13_amd64.deb
    source-type: deb
    stage-packages: 
      - git
      - gconf2
      - gconf-service
      - gvfs
      - gvfs-bin
      - libc6
      - libibus-1.0-5
      - libcap2
      - libgtk2.0-0
      - libgtk-3-0
      - libx11-xcb1
      - libxss1
      - libasound2
      - libatk-bridge2.0-0
      - libatspi2.0-0
      - libudev1
      - libgcrypt20
      - libnotify4
      - libnss3
      - libxtst6
      - python
      - xdg-utils
  kitematic-wrapper:
    plugin: dump
    source: snap/local
    override-build: |
      chmod +x wrapper
      chmod +x kitematic-snap.desktop
      snapcraftctl build
    stage:
      - usr/bin/wrapper
      - usr/share/applications/kitematic-snap.desktop
      - usr/share/pixmaps/kitematic-snap.png
    organize:
      wrapper: usr/bin/wrapper
      kitematic-snap.desktop: usr/share/applications/kitematic-snap.desktop
      kitematic-snap.png: usr/share/pixmaps/kitematic-snap.png

apps:
  kitematic:
    environment:
      PATH: $SNAP/usr/bin:$SNAP/bin/:$PATH
    desktop: usr/share/applications/kitematic-snap.desktop
    command: wrapper